### ISSUE TITLE
CircleCI failed due HTTP error

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/category_encoders-feedstock#1]
See this [build](https://circleci.com/gh/conda-forge/category_encoders-feedstock/1). Appears this failed due to some sort of download error when pulling `python` from `conda-forge`. Went ahead and restarted. If this builds through, please feel free to close.

**Comment by bollwyvl** [comment]
I see all the [linux builds](http://anaconda.org/conda-forge/category_encoders/files?version=1.2.2)! Thanks @jakirkham !
